import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react';
import styles from '../../styles/Home.module.css'
import { io } from "socket.io-client";

const socket = io('http://localhost:5021/chat');

export default function Home() {
  const router = useRouter();
  const { room } = router.query;

  interface MsgRes {
    time: string;
    msg: string;
    senderID: string;
  }

  const onSubmit = (data: { msg: string }) => {
    const req = {
      msg: data.msg,
      userID: '1',
    };
    console.log(req);
    socket.emit('msgToServer', req);
    //reset();
  };
  
  const [messages, setMessages] = useState<MsgRes[]>([]);
  
  useEffect(() => {
      socket.on('msgToClient', (res: MsgRes) => {
        setMessages(prev => [...prev, res]);
      });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

      <button onClick={() => onSubmit({msg: 'hello'})}>
        <h2>Room {room}</h2>
      </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
